name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov
    
    - name: Run tests
      run: |
        python -c "import torch; print('PyTorch version:', torch.__version__)"
        python -c "from src.model import LanguageClassifier, ImprovedLanguageClassifier; print('Models imported successfully')"
        python -c "from src.feature_extraction import word_to_ngram_features; print('Feature extraction imported successfully')"
    
    - name: Test model loading
      run: |
        python -c "
        import torch
        from src.model import ImprovedLanguageClassifier
        model = ImprovedLanguageClassifier(1000)
        print('Model created successfully')
        "

  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Build Docker image
      run: |
        docker build -t romance-classifier .
    
    - name: Test Docker container
      run: |
        docker run -d --name test-container -p 8000:8000 romance-classifier
        sleep 10
        curl -f http://localhost:8000/health || exit 1
        docker stop test-container
        docker rm test-container
    
    - name: Deploy to Streamlit Cloud
      env:
        STREAMLIT_SHARING_TOKEN: ${{ secrets.STREAMLIT_SHARING_TOKEN }}
      run: |
        echo "Deployment to Streamlit Cloud would happen here"
        # Add actual deployment commands when you have Streamlit Cloud setup




